{
  "name": "collaborative-whiteboard-root",
  "version": "1.0.0",
  "description": "Collaborative Whiteboard Server and Client",
  "main": "server.js",
  "scripts": {
    "start": "node server.js",
    "server": "node server.js",
    "client": "npm run dev --prefix client",
    "dev": "concurrently \"npm run server\" \"npm run client\"",
    "build": "npm install --prefix client && npm run build --prefix client"
  },
  "dependencies": {
    "cors": "^2.8.5",
    "express": "^4.19.2",
    "socket.io": "^4.7.5",
    "uuid": "^9.0.1"
  },
  "devDependencies": {
    "concurrently": "^8.2.2"
  }
}
